
@Library('MyLibrary') _
pipeline {
    agent any
    
    stages {

        stage ('checkout code from Git') {
            steps{
                script {checkout_git.checkout_git("Jenkinsfile" , "main")}
            }
        }
        
        stage('create tag on git repo') {
            steps {
                script  {create_tag.create_tag("${tag}")}
            }
        }
        
        


        
        
    }
    
}

